// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_bob_is_no_more = "CgkIucH5j-8YEAIQBg"; // <GPGSID>
        public const string achievement_kings_true_power = "CgkIucH5j-8YEAIQBw"; // <GPGSID>
        public const string achievement_monster_repelent_silver = "CgkIucH5j-8YEAIQAw"; // <GPGSID>
        public const string achievement_completionist = "CgkIucH5j-8YEAIQCg"; // <GPGSID>
        public const string achievement_monster_repelent_gold = "CgkIucH5j-8YEAIQBA"; // <GPGSID>
        public const string achievement_one_man_army = "CgkIucH5j-8YEAIQDA"; // <GPGSID>
        public const string achievement_monster_repelent_bronze = "CgkIucH5j-8YEAIQAg"; // <GPGSID>
        public const string achievement_put_your_friends__cat_in_the_game = "CgkIucH5j-8YEAIQCQ"; // <GPGSID>
        public const string achievement_true_one_man_army = "CgkIucH5j-8YEAIQDQ"; // <GPGSID>
        public const string achievement_who_made_this_piece_of_game = "CgkIucH5j-8YEAIQCw"; // <GPGSID>
        public const string achievement_monster_repelent_master = "CgkIucH5j-8YEAIQBQ"; // <GPGSID>

}

